progetto: benzinaio sem_mem macchina starter

starter: starter.c
	gcc starter.c -o starter

benzinaio: benzinaio.c
	gcc benzinaio.c -o benzinaio
	
sem_mem: sem_mem.c
	gcc sem_mem.c -o sem_mem
	
macchina: macchina.c
	gcc macchina.c -o macchina
