progetto: bin starter bin/sem_mem bin/benzinaio bin/macchina 

bin:
	mkdir bin

starter: src/starter.c
	gcc src/starter.c -o starter

bin/sem_mem: src/sem_mem.c
	gcc src/sem_mem.c -o bin/sem_mem

bin/benzinaio: src/benzinaio.c
	gcc src/benzinaio.c -o bin/benzinaio
	
bin/macchina: src/macchina.c
	gcc src/macchina.c -o bin/macchina
